### ISSUE TITLE
to get into production - for our ops team 

### ISSUE THREAD

**Issue by bryanhuntesl** [esl/elixirconf-eu-jekyll#18]
this jekyll site needs a CNAME file in the root directory 
DNS needs to be updated to point to this - docs - https://help.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages

**Comment by bryanhuntesl** [comment]
domain will be elixirconf.eu

**Comment by bryanhuntesl** [comment]
https://help.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages#using-an-apex-domain-for-your-github-pages-site

**Comment by kotewa** [comment]
website services should be  **www.elixirconf.eu** or **elixirconf.eu**
currrent website has www prefix

**Comment by lawrenced** [comment]
www.elixirconf.eu

**Comment by kotewa** [comment]
I have set TTL for 60s for elixirconf.eu domain,  so that DNS provisioning impact has been as small as possible.

**Comment by bryanhuntesl** [comment]
Site now live - thank you @kotewa

**Comment by kotewa** [comment]
current diagram with the archival pages:
docs: https://github.com/esl/infrastructure-docs/blob/master/services/elixirconf.eu/README.md
