### ISSUE TITLE
develop archive pages - ticket contains info about content and data 

### ISSUE THREAD

**Issue by bryanhuntesl** [esl/elixirconf-eu-jekyll#19]
You can communicate what you want to do with the old website content - the talks are converted from html to markdown and grouped by year, also, all the images are downloaded, csv files for resolving talk year, speaker, image, etc are provided. 

Also slides content from the previous years - it bloated up the repository quite a bit but we can always move elsewhere or [block via exclude](https://github.com/jekyll/jekyll/issues/257#issuecomment-631506) in _config.yml 

https://github.com/esl/elixirconf-eu-jekyll/tree/master/legacy-content
https://github.com/esl/elixirconf-eu-jekyll/blob/master/legacy-content/README.md
https://github.com/esl/elixirconf-eu-jekyll/blob/master/legacy-content/res/slides.csv
https://github.com/esl/elixirconf-eu-jekyll/blob/master/legacy-content/res/speakers.csv

**Comment by lawrenced** [comment]
We are currently working on a layout for these sections.

**Comment by lawrenced** [comment]
Looking at the archive section, is there an easy way for the same frontmatter that we have on current speakers to be pulled from these pages?

**Comment by bryanhuntesl** [comment]
Nope - manual process - I converted from HTML and cleaned them up a bit but this is a manual task.
