### ISSUE TITLE
Orderby - talks and training

### ISSUE THREAD

**Issue by lawrenced** [esl/elixirconf-eu-jekyll#24]
Some speakers, talks and training sources are more important than others.

We need a way to sort how the speakers appear.

So currently, for example, 'Chris McCord should be first, then 'Hans Josephsen' 

How can we organise these, could we add a key or something?

**Comment by victorldleon** [comment]
So I added a new property called **relevance** which is a number, so if you want to send an speaker to the   first position just set the relevance the desired position in the frontmatter property:
`relevance: 1`
for the second position:
`relevance: 2`
and so on ...

I added the sort_by relevance functionality to the speakers and trainers collections.

**Comment by lawrenced** [comment]
I’ve tried to do the ordering but doesn’t seem to work. Added Chris McCord as 1 but still not first.

**Comment by victorldleon** [comment]
It should be something related to the build since locally it works fine, I'll investigate more about it
