### ISSUE TITLE
Forestry integration 

### ISSUE THREAD

**Issue by lawrenced** [esl/elixirconf-eu-jekyll#25]
Need to be able to add new speakers, talks and blogs to the website using the CMS.

There is no speaker nor talk sections at the moment.

**Comment by lawrenced** [comment]
There's still issues with getting a full integration with forestry.

**Comment by bryanhuntesl** [comment]
Can you add a bit more detail please.

**Comment by bryanhuntesl** [comment]
"speaker nor talk section" - should have read it better - let me take a look...

**Comment by bryanhuntesl** [comment]
Ok - talks and speakers are in forestry.io CMS. There's a `_posts` directory too, I guess that corresponds with blog - there's some sample content in there but there isn't anything in current website to render that to the generated site. 

Let me know if this is still valid.
