### ISSUE TITLE
Newsletter Sign-up section - add sign-up form

### ISSUE THREAD

**Issue by lawrenced** [esl/elixirconf-eu-jekyll#29]
Need to have a sign-up to newsletter section.

Currently this is provided by an iframe from Pardot CMS.

Please add following code the the section: Add this code to the website:

<iframe allowtransparency="true" src="https://www2.erlang-solutions.com/l/23452/2017-01-25/4gngvx" style="border: 0" type="text/html" width="100%" height="200" frameborder="0"></iframe>

Please can the forms be styled so it fits in with the theme. (There is form css in the template)

**Comment by victorldleon** [comment]
I'm unable to apply the styles directly from the Jekyll css since it's an iframe, is it possible to style it in Pardot CMS?

**Comment by lawrenced** [comment]
yes its possible to add css within <style> in pardot. 
If you paste the code here, I will add it.

**Comment by victorldleon** [comment]
Here's the code:
`form.form p label {
  color: #ffffff;
  text-align: left;
}

form.form p.form-field {
  display: flex;
  flex-flow: column;
}

form.form input.text {
  background: rgba(255, 255, 255, 0.1);
  border: 1px solid #bdc3c7;
  color: #ffffff;
  display: inline-block;
  height: auto;
  font-size: 1rem;
  font-family: "Lato";
  margin-top: 5px;
  outline: 0;
  padding: 15px;
  position: relative;
  -webkit-transition: all 300ms ease-in-out;
  -o-transition: all 300ms ease-in-out;
  transition: all 300ms ease-in-out;
  width: 94%;
}

form.form p.submit {
  margin: 1em 0;
  padding: 0;
}

form.form p.submit input {
  background: rgba(255, 255, 255, 0.1);
  border-radius: 0.3em;
  display: inline-block;
  color: #ffffff;
  border: 2px solid #fff;
  cursor: pointer;
  font-size: 1rem;
  font-size: 1.3em;
  font-weight: 500;
  letter-spacing: 0.16em;
  max-width: 94%;
  margin: 20px auto 0 auto;
  font-weight: bold;
  padding: 0;
  text-align: center;
  width: 50%;
}
`

**Comment by lawrenced** [comment]
added following code to the iframe but its not working, any idea?

<!DOCTYPE html>
<html>
	<head>
		<base href="" >
		<meta charset="utf-8"/>
		<meta name="description" content="%%description%%"/>
		<title>%%title%%</title>
		<style>
  form.form p label {
  color: #ffffff;
  text-align: left;
}

form.form p.form-field {
  display: flex;
  flex-flow: column;
}

form.form input.text {
  background: rgba(255, 255, 255, 0.1);
  border: 1px solid #bdc3c7;
  color: #ffffff;
  display: inline-block;
  height: auto;
  font-size: 1rem;
  font-family: "Lato";
  margin-top: 5px;
  outline: 0;
  padding: 15px;
  position: relative;
  -webkit-transition: all 300ms ease-in-out;
  -o-transition: all 300ms ease-in-out;
  transition: all 300ms ease-in-out;
  width: 94%;
}

form.form p.submit {
  margin: 1em 0;
  padding: 0;
}

form.form p.submit input {
  background: rgba(255, 255, 255, 0.1);
  border-radius: 0.3em;
  display: inline-block;
  color: #ffffff;
  border: 2px solid #fff;
  cursor: pointer;
  font-size: 1rem;
  font-size: 1.3em;
  font-weight: 500;
  letter-spacing: 0.16em;
  max-width: 94%;
  margin: 20px auto 0 auto;
  font-weight: bold;
  padding: 0;
  text-align: center;
  width: 50%;
}
</style>
	</head>

	<body>
		%%content%%
	</body>
</html>

**Comment by victorldleon** [comment]
Maybe a new Iframe has been generated after you added the css code, if so can you paste it here?

**Comment by lawrenced** [comment]
Tried still not working, think it’s a css class authority/weighting issue, need to chain it more with more divs and IDs. Tried !important and that worked in test bed but not in your file.

**Comment by victorldleon** [comment]
It looks like It's working is just the button what looks weird

**Comment by victorldleon** [comment]
this will fix the button:

```
form.form p.submit input {
    background: rgba(255, 255, 255, 0.1) !important;
    border-radius: 0.3em !important;
    display: inline-block !important;
    color: #ffffff !important;
    border: 2px solid #fff !important;
    cursor: pointer !important;
    font-size: 1rem !important;
    font-size: 1.3em !important;
    font-weight: 300 !important;
    letter-spacing: 0.16em !important;
    max-width: 94% !important;
    margin: 20px auto 0 7px !important;
    font-weight: bold !important;
    padding: 12px !important;
    text-align: center !important;
    width: 50% !important;
}
```

**Comment by lawrenced** [comment]
Can we style the button better when on mobile, the new style doesnt transfer to iphone
