### ISSUE TITLE
frontmatter changes speaker pages

### ISSUE THREAD

**Issue by lawrenced** [esl/elixirconf-eu-jekyll#32]
Need to add the following to frontmatter:

talk:
talk description:

>change 'description:' to 'bio:'

-these then need to be updated in the loop and in speaker pages.

**Comment by lawrenced** [comment]
UPDATE:

added a speaker in following format, this is final,
so need to add

talk
abstract
audience
>and change description to bio

short_name: ju-liu
pic_url: ju-liu.jpg
firstname: Ju
lastname: Liu
position: Troublemaker
talk: Filling your house with little Nerves robots
abstract: We fill our homes with devices over which we have little or no control. Our speakers, doorbells, televisions, and fridges are getting smart. We are getting used to relinquishing our privacy and our lives to random startups that won't hesitate a second to sell our data to the highest bidder. But what if we went rogue? What if we took back control? In this talk, I will explain how to replace devices over which you have no control with devices over which you have absolute and complete control. We will see how easy it is to build smart devices which are safe and privacy conscious, thanks to the powers of Elixir and Nerves. At the end of the talk, you should feel confident to go out there and build your own reliable, discreet and smart Nervous assistants.
audience: Intermediate
bio: Ju was born in China, moved to Italy as a kid, grew up eating a lot of pasta, and started messing around with computers. He now lives in London and works for NoRedInk. He loves to solve interesting problems and build amazing products. When heâ€™s not doing that, heâ€™s probably rock climbing.
twitter: arkh4m
github: Arkham

**Comment by victorldleon** [comment]
where should I add the **abstract** part?
