### ISSUE TITLE
Training and trainers - not pairing

### ISSUE THREAD

**Issue by lawrenced** [esl/elixirconf-eu-jekyll#43]
The trainers are only showing one trainer for training that has two trainers. They are also not organising based on relevance.

The training should be like the following:

Training: Elixir Testing: From Zero to Hero with Devon Estes
Trainer: Devon Estes

Training: From Zero To Hero With Elixir 
Trainer: Eric Meadows-Jönsson
Trainer2: Andrea Leopardi

Training: Debugging A Running System with Ben Marx
Trainer: Ben Marx
Trainer2: Justin Schneck

Training: Getting up to speed with Phoenix and LiveView 
Trainer: Shankar Dhanasekaran

Training: Phoenix LiveView from Prototype to Production
Trainer: Tam Kbeili
Trainer2: Mike Martinson

Training: Ecto - From The Ground Up
Trainer: Darin Wilson
Trainer2: Wojtek Mach

**Comment by lawrenced** [comment]
This issue is in both the training box and on the training pages.

**Comment by victorldleon** [comment]
For the training box there is a file in **_data/training.yml** which in this case has to be edited manually since the type of design that has three columns per row ( one for the hours and the other two for each talk in that hour).

If you'd want the box to be dynamic and loop through the MD files in the **_trainings** folder we need to get rid of the third column and only keep the **hours** and one **training** per row.

**Comment by victorldleon** [comment]
I changed the structure of the training a little it looks like this now:

```
---
trainer: eric-meadows
trainer-2: andrea-leopardi
trainer-name: Eric Meadows
trainer-name-2: Andrea Leopardi
event_date: 28 April
venue: Centrum Konferencyjne, Golden Floor Tower, ul. Chłodna 51, 00-867 Warszawa
summary: This is an example of a description of the training
description: this is an example of the description about the training
experience: Beginner, Intermediate
from: 11.30 AM
to: 12.30 PM
type: training
---
```

**Comment by victorldleon** [comment]
Now it shows both names in the training layout, also added some logic to display the training link in each speaker or trainer related to the training.
