### ISSUE TITLE
Items stopping the website going live - broken keynote links and missing training details

### ISSUE THREAD

**Issue by lawrenced** [esl/elixirconf-eu-jekyll#50]
1
When you click on any of the keynotes, in the keynotes section, their profile pages do not display. You just get the text at the top and no template attached.
2
In the training section, when you click on trainers, on photo or name, we only get their bio, we dont get the training details.
3
Also the training details do not show up on some training, these have been added as front matter, they need to be added as content.
4
Top section - I added diversity but it is not linking
5
when you paste the link, can we make sure it says ElixirConf EU 2020 in the meta details? Not sure if this is because it isnt live yet.

**Comment by victorldleon** [comment]
So I restructured the keynotes, I added all keynotes and speakers in the speakers folder but added a frontmatter property called type, which can be type: keynote or type: speaker that way we can filter them accord.

About point 4 It wasn't linking because there wasn't any diversity section yet, which I just added.

In regards the meta data It's possible that they are not showing since the site isn't live, but in this case we need to test it when the site It's live.

Also the missing info in trainings was added and I removed the frontmatter properties of summary and description, so that info can be added as content.

```
now the training MD file looks like this:

---
trainer: wojtek-mach
trainer-name: Wojtek Mach
trainer-2: darin-wilson
trainer-name-2: Darin Wilson
event_date: 28 April
venue: Centrum Konferencyjne, Golden Floor Tower, ul. Chłodna 51, 00-867 Warszawa
experience: Beginner, Intermediate
from: 09.00
to: 17.00
type: training
---

# Heading level 1

## Heading level 2

### Heading level 3

#### Heading level 4

##### Heading level 5

###### Heading level 6

I really like using Markdown.

I think I'll use it to format all of my documents from now on.

This is the first line.  
And this is the second line.

I just love **bold text**.
I just love **bold text**.
Love**is**bold

This text is **_really important_**.

> Dorothy followed her through many of the beautiful rooms in her castle.

1. First item
2. Second item
3. Third item
4. Fourth item

- First item
- Second item
- Third item
- Fourth item

- First item
- Second item
- Third item
  - Indented item
  - Indented item
- Fourth item

1.  Open the file containing the Linux mascot.
2.  Marvel at its beauty.

    ![Tux, the Linux mascot](https://via.placeholder.com/550)

3.  Close the file.

`` Use `code` in your Markdown file. ``

My favorite search engine is [Duck Duck Go](https://duckduckgo.com).

<https://www.markdownguide.org>
<fake@example.com>

```

**Comment by lawrenced** [comment]
Thanks for the update with the type:keynote addition, If a speaker type is a keynote then it needs to not be shown in the speaker section and only in the keynote section. We can't have a duplicate of a speaker showing in two sections. 

Perhaps some form of if statement, if type not keynote then show  etc..

**Comment by lawrenced** [comment]
Also, if speaker is keynote, we need to also NOT show the audience type - as keynotes are for all and so audience definition ceases to be important. So the same logic to apply keynotes could be added to show audience only for non keynotes.

**Comment by lawrenced** [comment]
Also, the trainer's training course/title is not showing if you click on trainer name/photo in the training section.

**Comment by victorldleon** [comment]
My bad, I added the filter to show only the speakers in the speakers section, fixed the bug for the training not showing in each trainer, and also hide the audience type for the keynotes
